import { EVOLUTION_PHASES, EVOLUTION_RARITY, createEvolutionStage } from './evolutions.js';
export const butterflySpecies = { key: 'butterfly', name: 'Butterfly', baseStats: { hp: 8, atk: 2, def: 2, spd: 15 }, growthStats: { hp: 2, atk: 1, def: 1, spd: 4 }, type: 'swift', diet: 'herbivore',
  evolutions: {
    1: { ...createEvolutionStage(1, 'Butterfly Caterpillar', 'Tiny caterpillar munching leaves', EVOLUTION_PHASES.BABY), bonuses: {}, abilities: ['flutter', 'pollen_dust'] },
    2: { ...createEvolutionStage(2, 'Butterfly', 'Beautiful butterfly with delicate wings', EVOLUTION_PHASES.YOUNG), bonuses: { spd: 0.16, atk: 0.08 }, abilities: ['flutter', 'pollen_dust', 'wind_gust'] },
    3: { ...createEvolutionStage(3, 'Butterfly', 'Graceful flyer with vibrant colors', EVOLUTION_PHASES.ADULT), bonuses: { spd: 0.24, atk: 0.12, def: 0.02 }, abilities: ['flutter', 'pollen_dust', 'wind_gust', 'aerial_dodge'] },
    4: { ...createEvolutionStage(4, 'Butterfly', 'Ancient butterfly, master of winds', EVOLUTION_PHASES.ELDER), bonuses: { spd: 0.32, atk: 0.18, def: 0.04, luck: 0.1 }, abilities: ['flutter', 'pollen_dust', 'wind_gust', 'aerial_dodge', 'whirlwind'] },
    5: { ...createEvolutionStage(5, 'Crystal Butterfly', 'Butterfly of crystalline beauty', EVOLUTION_PHASES.BABY, EVOLUTION_RARITY.UNCOMMON), bonuses: { spd: 0.18, def: 0.06 }, abilities: ['flutter', 'pollen_dust', 'crystal_dust'] },
    6: { ...createEvolutionStage(6, 'Crystal Butterfly', 'Sparkling butterfly of gems', EVOLUTION_PHASES.YOUNG, EVOLUTION_RARITY.UNCOMMON), bonuses: { spd: 0.28, atk: 0.1, def: 0.08 }, abilities: ['flutter', 'pollen_dust', 'crystal_dust', 'reflect', 'gem_aura'] },
    7: { ...createEvolutionStage(7, 'Crystal Butterfly', 'Radiant butterfly of pure crystal', EVOLUTION_PHASES.ADULT, EVOLUTION_RARITY.UNCOMMON), bonuses: { spd: 0.36, atk: 0.14, def: 0.12, luck: 0.08 }, abilities: ['flutter', 'pollen_dust', 'crystal_dust', 'reflect', 'gem_aura', 'prismatic_wing'] },
    8: { ...createEvolutionStage(8, 'Crystal Butterfly', 'Ancient crystal given flight', EVOLUTION_PHASES.ELDER, EVOLUTION_RARITY.UNCOMMON), bonuses: { spd: 0.44, atk: 0.2, def: 0.16, crystalline: 0.3 }, abilities: ['flutter', 'pollen_dust', 'crystal_dust', 'reflect', 'gem_aura', 'prismatic_wing', 'diamond_flight'] },
    9: { ...createEvolutionStage(9, 'Void Butterfly', 'Butterfly transcending reality', EVOLUTION_PHASES.ELDER, EVOLUTION_RARITY.SUPERNATURAL), bonuses: { spd: 0.64, atk: 0.3, def: 0.24, infiniteWings: 0.8, voidFlight: 1.0 }, abilities: ['flutter', 'pollen_dust', 'crystal_dust', 'reflect', 'gem_aura', 'prismatic_wing', 'diamond_flight', 'void_wing', 'reality_flutter'] }
  },
  legendaryForm: { number: 10, name: 'Celestial Butterfly', description: 'Divine butterfly blessed by starlight', growth: EVOLUTION_PHASES.ELDER, rarity: EVOLUTION_RARITY.LEGENDARY, epCost: 2400, requirements: { minLevel: 45, minStats: { atk: 30, def: 25, spd: 75 }, minBattlesWon: 500, epThreshold: 4000, rareItems: 3 }, bonuses: { spd: 0.5, atk: 0.25, def: 0.1, luck: 0.4, celestialWings: 0.6 }, abilities: ['flutter', 'pollen_dust', 'wind_gust', 'aerial_dodge', 'whirlwind', 'stellar_flutter'] },
  ancientForm: { number: 11, name: 'Primordial Butterfly', description: 'Ancient butterfly from creation\'s age', growth: EVOLUTION_PHASES.ELDER, rarity: EVOLUTION_RARITY.ANCIENT, epCost: 3600, requirements: { minLevel: 65, minStats: { atk: 45, def: 40, spd: 105 }, minBattlesWon: 1500, epThreshold: 7500, rareItems: 5, timePlayed: 500 }, bonuses: { spd: 0.7, atk: 0.35, def: 0.18, primalWings: 0.9, ancestralFlight: 0.8 }, abilities: ['flutter', 'pollen_dust', 'wind_gust', 'aerial_dodge', 'whirlwind', 'primal_flight'] },
  supernaturalForm: { number: 12, name: 'Entity of Flight', description: 'Incomprehensible being of infinite motion', growth: EVOLUTION_PHASES.ELDER, rarity: EVOLUTION_RARITY.SUPERNATURAL, epCost: 6000, requirements: { minLevel: 100, minStats: { atk: 100, def: 95, spd: 180 }, minBattlesWon: 3000, epThreshold: 15000, rareItems: 10, timePlayed: 1000, specialItems: ['essence_of_chaos', 'void_crystal', 'eternal_flame'] }, bonuses: { spd: 1.4, atk: 0.5, def: 0.35, supernaturalFlight: 2.2, voidWings: 2.0, infiniteMotion: 1.0 }, abilities: ['flutter', 'void_wing', 'reality_flutter', 'void_phase', 'chaos_flight', 'infinity_speed'] },
  statUpgrades: {
    swiftness: { name: 'Swiftness', description: 'Increases speed and agility', costPerPoint: 2, maxPoints: 60, effect: (points) => ({ spd: points * 0.15, agility: points * 0.005 }) },
    grace: { name: 'Grace', description: 'Improves evasion and dodge', costPerPoint: 2, maxPoints: 50, effect: (points) => ({ spd: points * 0.1, evasion: points * 0.006 }) },
    aura: { name: 'Aura', description: 'Enhances magical presence', costPerPoint: 3, maxPoints: 40, effect: (points) => ({ atk: points * 0.08, luck: points * 0.006 }) }
  }
};
